name: Build Compotes app.

on:
    push:
        branches:
            - release

jobs:
    build:
        strategy:
            fail-fast: false
            matrix:
                os:
                    - ubuntu-latest
                    - windows-latest

        runs-on: ${{ matrix.os }}
        steps:
            - { name: "Checkout the code", uses: actions/checkout@v2 }

            - name: 🗄️ Setup Rust cache
              uses: actions/cache@v2
              with:
                  key: ${{ matrix.os }}-${{ hashFiles('src-tauri/Cargo.lock') }}
                  path: |
                      ~/.cargo/registry/index
                      ~/.cargo/registry/cache
                      ~/.cargo/git
                      ./src-tauri/target

            - name: 🍃 Install Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 16
                  cache: yarn
                  cache-dependency-path: |
                      yarn.lock
                      tests/webdriverio/yarn.lock

            - name: 🦀 Install Rust
              uses: actions-rs/toolchain@v1
              with: { toolchain: stable }

            - name: 🌐 Update MSEdge webdriver (windowsonly)
              if: matrix.os == 'windows-latest'
              run: |
                  choco upgrade microsoft-edge

            - name: 🌐 Install webkit2gtk (ubuntu only)
              if: matrix.os == 'ubuntu-latest'
              run: |
                  sudo apt-get update
                  sudo apt-get upgrade -y --no-install-recommends -y libgtk-3-dev libgtksourceview-3.0-dev webkit2gtk-4.0 libappindicator3-dev webkit2gtk-driver xvfb

            - name: 🔌 Install Node.js dependencies
              run: yarn install

            - name: 🔌 Download Rust dependencies
              run: cargo fetch --manifest-path=src-tauri/Cargo.toml

            - name: 🏗️ 📄 Build frontend
              run: yarn build

            - name: 🏗️ 💽 Build application
              run: yarn tauri build

            - name: 🚀 Upload release artifacts
              uses: actions/upload-artifact@v2
              with:
                  name: release-${{ matrix.os }}
                  path: |
                      src-tauri/target/release/compotes*
                      src-tauri/target/release/bundle/*
